### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by cryptax** [ANSSI-FR/Binacle#1]
Hi,

I'm trying to build Binacle, but it fails:

```
cargo build --release --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to parse registry's information for: serde_derive

Caused by:
  the given version requirement is invalid
```

My system :

- Linux Mint
- Installed cargo 0.8.0 with `apt-get install cargo`
- Fresh git clone of repository from today

Thanks for your help :)

**Comment by 0xDeva** [comment]
The current cargo version is 0.18.0, please use an updated version of it (or a real OS).

**Comment by cryptax** [comment]
Okay - it works with cargo 0.19.0 - issue can be closed
(lol for the real OS, no comment).
