### ISSUE TITLE
Recursive add of files in database not working correctly

### ISSUE THREAD

**Issue by cryptax** [ANSSI-FR/Binacle#2]
I asked binacle to add an entire directory (120 samples) but I don't think it's working. Looks like it is only adding one sample. And the database is suspiciously small.

I created my database with `binacle -c /collections/sampledb map 30000000000 6 28`.
Then, I put several binary samples in `/tmp/binacle-tmp`:
```
$ ls -l /tmp/binacle-tmp/ | head
total 261052
-rw-r--r-- 1 axelle axelle  861912 Jun 13 12:27 classes.dex
-rw-r--r-- 1 axelle axelle 5463104 Jun 13 12:29 classes.dex.1
-rw-r--r-- 1 axelle axelle 3238196 Jun 13 12:29 classes.dex.10
-rw-r--r-- 1 axelle axelle 3934256 Jun 13 12:29 classes.dex.100
-rw-r--r-- 1 axelle axelle 3806456 Jun 13 12:29 classes.dex.101
-rw-r--r-- 1 axelle axelle  796380 Jun 13 12:29 classes.dex.102
-rw-r--r-- 1 axelle axelle  818452 Jun 13 12:29 classes.dex.103
-rw-r--r-- 1 axelle axelle  792500 Jun 13 12:29 classes.dex.104
-rw-r--r-- 1 axelle axelle 5941540 Jun 13 12:29 classes.dex.105
$ ls -l /tmp/binacle-tmp/ | wc -l
120
```

Then, I added them to binacle's database:

```bash
$ ~/softs/Binacle/target/release/binacle /collections/sampledb --rec /tmp/binacle-tmp
Inserting file 100 (size 1040572) "/tmp/binacle-tmp/classes.dex.57"
```
Isn't it strange that it tells me it inserts `file 100` (when I have 120), and only mentions `classes.dex.57`?

I checked the size of the database. It's too small to be real...
```bash
$ ls -lh /collections/sampledb
-rw-r--r-- 1 axelle axelle 125 Jun 13 12:34 /collections/sampledb
```

Your demo is on Windows. Are you sure this works over Linux?

Thanks

**Comment by 0xDeva** [comment]
Can you paste the content of the file /collections/sampledb_index0.meta please ?
It indicates how many samples are in the index ("nb_file" should be 120), thanks!

- Isn't it strange that it tells me it inserts file 100 (when I have 120), and only mentions classes.dex.57?

No, it isn't, the log is generated every 100 files, it displays the name of the current file being inserted.
There is no guarantee that your files are inserted in the lexicographic order.

**Comment by 0xDeva** [comment]
- Your demo is on Windows. Are you sure this works over Linux?

I just tried on a fresh ubuntu and it works.

1. cp /bin/* test/
2. target/release/binacle -c database/sampledb map 30000000000 6 28
3. time target/release/binacle database/sampledb --rec test/
Inserting file 100 (size 154072) "test/dash"
real 0m6.114s
user 0m1.300s
sys 0m0.852s

The file database/sampledb_index0.meta indicates that nb_file=160, which is the number of files in test/

**Comment by cryptax** [comment]
> Can you paste the content of the file /collections/sampledb_index0.meta please ?

```bash
$ cat sampledb_index0.meta
{"size":1342177344,"offset_size":5,"alignment":6,"ngram_size":28,"nb_file":0,"last_id":0,"average_size":0.0}
```

Doesn't look good.

I also tried the command with a relative path to my /tmp/binacle-tmp dir, but did not change anything. Same issue.

**Comment by 0xDeva** [comment]
I have tried with "/collections/sampledb" and "/tmp/binacle-tmp" like in your example on my Ubuntu VM, it also worked (with sudo rights).
Can you send me your test-case and your compiled binary ?
Can you try using paths relative to your /home ?
Thanks

**Comment by cryptax** [comment]
> Can you try using paths relative to your /home ?

I've put the samples in a subdir of target/release, and the database in the directory of binacle.
It works :))

```bash
$ ./binacle sampledb --rec ./samples/
$ ./binacle sampledb -s getDeviceId # Example: lists all Android samples retrieving IMEI ;)
$ ./binacle sampledb -s hex 6465780a303335 # finds all DEX 035 files
```

>I have tried with "/collections/sampledb" and "/tmp/binacle-tmp" like in your example on my Ubuntu VM, it also worked (with sudo rights).

nb. Why sudo?

So, there's probably an issue with paths, but with relative ones, it works. Thanks!
