### ISSUE TITLE
Installed Failed 

### ISSUE THREAD

**Issue by sebdraven** [ANSSI-FR/Binacle#3]
Hi, 
I try to install binacle and I've this error at compilation.

error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
  --> /home/slarinier/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.9/src/lib.rs:33:1
   |
33 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `serde_derive`.

rustc 1.16.0

Have you got a work arround ?

Thank for your feed back

**Comment by 0xDeva** [comment]
Hi, 

Can you write the command line you are using to compile the project ? 

Can you try to update cargo to 1.17.0 ? 

Thanks.

**Comment by sebdraven** [comment]
Thanks for your reply,

 cargo build --release
   Compiling serde_derive v1.0.9
error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
  --> /home/slarinier/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.9/src/lib.rs:33:1
   |
33 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `serde_derive`.

To learn more, run the command again with --verbose.

cargo-0.17.0 (built 2017-03-24)

**Comment by 0xDeva** [comment]
I didn't manage to reproduce this bug, it seems linked to https://github.com/paritytech/parity-bitcoin/issues/411.

**Comment by sebdraven** [comment]
So I've arrive to install after install rustup to install rust and cargo I make a PR to make the documentation :)
